### ISSUE TITLE
Fix version and tag

### ISSUE THREAD

**Issue by franz-josef-kaiser** [medikoo/d#10]
Currently the [`package.json`](https://github.com/medikoo/d/blob/f9031455a5012c23bb85a3eec93007df302b3a64/package.json#L3) has a version of `1.0.0`, while the [latest release currently is 0.1.1](https://github.com/medikoo/d/releases). Could you please tag the commit and also deploy a new version on NPM? Thanks in advance.

**Comment by medikoo** [comment]
@franz-josef-kaiser I stopped doing that, as adding release always needs to be done manually.
Why it's important for you? You certainly have valid point, but I'd like to understand for what reasons devs use that feature (it's npm where versions are released not github)

**Comment by franz-josef-kaiser** [comment]
When I switch releases in a package manager, then it's easier to have both the plain resources (git, zip) and as well the package manager packages. Also `npm shrinkwrap` complained about a pkg that used your package and it was unable to nail down the version (using a 6.x Nodejs version).

**Comment by medikoo** [comment]
> Also `npm shrinkwrap` complained about a pkg that used your package and it was unable to nail down the version (using a 6.x Nodejs version).

Thanks insteresting, do you suggest that _npm shrinkwrap_ relies on github releases? It would be a big surprise to me.

**Comment by franz-josef-kaiser** [comment]
> npm shrinkwrap relies on github releases?

I am not completely sure if it does that. Aside from _Composer_, all other package manager internals are unknown to me. I just came here as the npm debug stacktrace pointed its trace back to this plugin. Package managers normally are capable using different mechanisms of delivery to use fallbacks in case some route does not work out: streams, tarballs, zips, vcs checkouts, you choose.

Btw, if you do not have a tag on GitHub and do not want to push one, you can simply open the [releases tab](https://github.com/medikoo/d/releases), enter a version number and then just (as [per the docs](https://help.github.com/articles/creating-releases/)) get a new tag created for you.

**Comment by medikoo** [comment]
> I just came here as the npm debug stacktrace pointed its trace back to this plugin.

npm for sure doesn't depend on github releases. I'm closing it as it's for sure not relevant to your issue
