### ISSUE TITLE
No Longer Available on NPM

### ISSUE THREAD

**Issue by mssngr** [medikoo/d#16]
This package has been removed from NPM. Caused our production builds to fail.

**Comment by medikoo** [comment]
Why did you assume that? `d` is in npm registry as it always was: https://www.npmjs.com/package/d

**Comment by mssngr** [comment]
![Screen Shot 2020-06-25 at 1 59 42 PM](https://user-images.githubusercontent.com/23464169/85799127-f152bf80-b6fb-11ea-82c8-28a9fcaab479.png)

```
npm WARN deprecated D@1.0.0: Package no longer supported. Contact support@npmjs.com for more info.
```

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for D@1.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'venona-specs-tools'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p2813835/.npm/_logs/2020-06-25T20_11_16_625Z-debug.log
```

npm debug log
```
1425 silly fetchPackageMetaData error for d@^1.0.1 No matching version found for D@^1.0.1.
```

We were using memoize, which required `d`.

![02_01_16](https://user-images.githubusercontent.com/23464169/85799210-18a98c80-b6fc-11ea-92a4-8c042f584231.jpg)

However, because of `d` no longer existing in NPM, we had to replace all our usage of `memoizee` with `mem`. Multiple teams at my company are having to do the same thing.

**Comment by mssngr** [comment]
Sorry to waste your time! You were right, was a registry issue. We use Artifactory, which mirrors NPM. Someone in the company uploaded a package called `d` with version 1.0.1. And thus, they broke everyone's repos in the whole company 😂.

**Comment by medikoo** [comment]
@mssngr thanks for feedback. Good to see you coined the source of the issue

**Comment by PhilomathJ** [comment]
I'm getting this exact same error but with "npm install gulp-cli". I fail to believe gulp let this break their code, but I can't see how to remove the dependency before install

**Comment by hanweiit007** [comment]
There is no problem using NPM version 6+, but in npm7, there will be errors when updating.
<img width="553" alt="截屏2021-03-30 14 44 04" src="https://user-images.githubusercontent.com/14070903/112944941-2a75ff80-9166-11eb-9108-96d7b6574bb3.png">

**Comment by medikoo** [comment]
@hanweiit007 this package is named `d` not `D`

**Comment by hanweiit007** [comment]
I didn't add d@1.0.1 dependency, It is dependent on gulp.
<img width="231" alt="截屏2021-03-30 14 46 04" src="https://user-images.githubusercontent.com/14070903/112945304-b2f4a000-9166-11eb-968b-e6d64ec6930e.png">

**Comment by medikoo** [comment]
@hanweiit007 `d` and `D` are different packages. You're first comment lists `D`.

If your package manager installed `D` instead of `d` where it's `d` that's expected then it's a bug in package manager and it should be reported in its issue tracker.

**Comment by hanweiit007** [comment]
@medikoo My problem has been solved.
The package doesn't exist in our company's depository. I used other depository to complete the update.
thank you！
