### ISSUE TITLE
How to properly uninstall d@1.0.1 package

### ISSUE THREAD

**Issue by JF0001** [medikoo/d#17]
I have installed node-gyp globally in order to install scrypt. While installing the node-gyp package, the d@1.0.1 package was installed along with it. Realising that I did not need the node-gyp and scrypt packages, I have tried to remove the d@1.0.1 package, but sudo npm uninstall does not remove it. How can I properly uninstall this packages?

Thank you. J

**Comment by medikoo** [comment]
@JF0001 this is a question you should rather put at package manager forum and not here. `d` doesn't imply any install or uninstall logic. It's package manager that does it.

**Comment by JF0001** [comment]
Thank you @medikoo Yes indeed, I understand and agree. However, since npm appears to be working for pretty much anything else, I thought that perhaps `d` may be implementing something "non-standard". In any case, I guess just removing the corresponding folder in the node_modules directory should be sufficient, right?

Thank you again. J

**Comment by medikoo** [comment]
>  I guess just removing the corresponding folder in the node_modules directory should be sufficient, right?

I think that should work (assuming it won't break some other packages).

Otherwise `d` is very basic, and doesn't do anything custom. It's as simple as it can be npm package with no script hooks configured

**Comment by JF0001** [comment]
Thank you @medikoo
