### ISSUE TITLE
Rename the package?

### ISSUE THREAD

**Issue by y-nk** [medikoo/d#19]
Hello,

I'd like to formerly ask if you could reconsider the name of your package for something _more meaningful_. It's hard to know what a single letter package does, and there's another reason as well... Mistyping an `npm i` command by forgetting the `-` would install your package. Typing `npm i d react` (install `d` and `react` instead of mistyped `react -d`). There's also a `-` pacakge on npm, so mistyping a space would install both `-` and `d` packages.

Your lib seems cool, please don't troll other people.

**Comment by medikoo** [comment]
@y-nk thanks for request.

Package is intentionally named `d`, as it's de-sugaring verbose descriptors constructs into something that is not as noisy (ideally invisible). Please follow documentation for more details.

In long live of a package (first time released 8 years ago) it's a first time that someone complains about name, therefore I assume that confusion you've reached is extremely rare and should not be considered as a significant issue.

**Comment by y-nk** [comment]
Thanks for the meaningful feedback.

It's been brought recently to light as part of an other abusively named package `-` which creates the rather annoying case of confusion:

`npm i -d react`
`npm i - d react`

I hope you see where I'm getting with that.

**Comment by medikoo** [comment]
@y-nk this package is for over 8 years in operation, it is used indirectly by 3+ million of projects. I don't think it's a good idea to rename it cause of a single report.
